test_fenetre : div_fenetre.c test_div_fen.c div_fenetre.h file_dynamique.h file_dynamique.c element_P2.h element_P2.c
	gcc -c div_fenetre.c -g
	gcc -c test_div_fen.c -g
	gcc -c file_dynamique.c -g
	gcc -c element_P2.c -g
	gcc -o test_fen.out  div_fenetre.o test_div_fen.o file_dynamique.o element_P2.o
